/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikasir_ujikom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat; 
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author user
 */
public class FormLapTran extends javax.swing.JFrame {
    Connection konek;
    PreparedStatement pst, pst2;
    ResultSet rst;
    String tanggal,tanggal2,sql;
    /**
     * Creates new form FormLapTran
     */
    public FormLapTran() {
        initComponents();
        konek =  Koneksi.koneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sebelumtgl = new com.toedter.calendar.JDateChooser();
        daritgl = new com.toedter.calendar.JDateChooser();
        setelahtgl = new com.toedter.calendar.JDateChooser();
        btncari1 = new javax.swing.JButton();
        btncari2 = new javax.swing.JButton();
        btncari3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        sampaitgl = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldataproduk = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbllaptransaksi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Sebelum Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, -1));

        jLabel3.setText("Diantara Tanggal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 90, -1));

        jLabel4.setText("Sesudah Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));
        getContentPane().add(sebelumtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 170, -1));
        getContentPane().add(daritgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 150, -1));
        getContentPane().add(setelahtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 170, -1));

        btncari1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\icons8-search-20.png")); // NOI18N
        btncari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        btncari2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\icons8-search-20.png")); // NOI18N
        btncari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari2ActionPerformed(evt);
            }
        });
        getContentPane().add(btncari2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        btncari3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\icons8-search-20.png")); // NOI18N
        btncari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari3ActionPerformed(evt);
            }
        });
        getContentPane().add(btncari3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, -1));

        jLabel5.setText("s/d");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 20, -1));
        getContentPane().add(sampaitgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 160, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        jLabel6.setText("Laporan Transaksi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 350, 50));

        tbldataproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DetailID", "ProdukID", "Harga", "JumlahProduk", "Subtotal"
            }
        ));
        tbldataproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldataprodukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbldataproduk);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 500, 160));

        tbllaptransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PenjualanID", "DetailID", "TanggalPenjualan", "JamPenjualan", "TotalHarga"
            }
        ));
        tbllaptransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbllaptransaksiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbllaptransaksi);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 160));

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 75, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Camera Roll\\bg-lap.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbldataprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldataprodukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbldataprodukMouseClicked

    private void tbllaptransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbllaptransaksiMouseClicked
try{
    int row = tbllaptransaksi.getSelectedRow();
    String tabelKlik = (tbllaptransaksi.getModel().getValueAt( row,  1).toString());
    String sql = "select * from detail_penjualan where DetailID=?";
    pst = konek.prepareStatement(sql);
    pst.setString(1,tabelKlik);
    rst = pst.executeQuery();
    tbldataproduk.setModel(DbUtils.resultSetToTableModel(rst));
}catch (Exception e){
    JOptionPane.showMessageDialog( null,e);
}// TODO add your handling code here:
    }//GEN-LAST:event_tbllaptransaksiMouseClicked

    private void btncari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari1ActionPerformed
try {
    SimpleDateFormat format = new SimpleDateFormat("yyy-MM-dd");
    tanggal = format.format(sebelumtgl.getDate());
    sql = "select * from penjualan where TanggalPenjualan < '"+tanggal+"'";
    pst = konek.prepareStatement(sql);
    rst = pst.executeQuery();
    tbllaptransaksi.setModel(DbUtils.resultSetToTableModel(rst));
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "Data Tidak Tampil");
}
    }//GEN-LAST:event_btncari1ActionPerformed

    private void btncari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari2ActionPerformed
try {
    SimpleDateFormat format = new SimpleDateFormat("yyy-MM-dd");
    tanggal = format.format(daritgl.getDate());
    tanggal2 = format.format(sampaitgl.getDate());
    sql = "select * from penjualan where TanggalPenjualan between '"+tanggal+"' and '"+tanggal2+"' ";
    pst = konek.prepareStatement(sql);
    rst = pst.executeQuery();
    tbllaptransaksi.setModel(DbUtils.resultSetToTableModel(rst));
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "Data Tidak Tampil");
}       // TODO add your handling code here:
    }//GEN-LAST:event_btncari2ActionPerformed

    private void btncari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari3ActionPerformed
try {
    SimpleDateFormat format = new SimpleDateFormat("yyy-MM-dd");
    tanggal = format.format(setelahtgl.getDate());
    sql = "select * from penjualan where TanggalPenjualan > '"+tanggal+"'";
    pst = konek.prepareStatement(sql);
    rst = pst.executeQuery();
    tbllaptransaksi.setModel(DbUtils.resultSetToTableModel(rst));
}catch (Exception e){
    JOptionPane.showMessageDialog(null, "Data Tidak Tampil");
}        // TODO add your handling code here:
    }//GEN-LAST:event_btncari3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLapTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLapTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLapTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLapTran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLapTran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari1;
    private javax.swing.JButton btncari2;
    private javax.swing.JButton btncari3;
    private com.toedter.calendar.JDateChooser daritgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.toedter.calendar.JDateChooser sampaitgl;
    private com.toedter.calendar.JDateChooser sebelumtgl;
    private com.toedter.calendar.JDateChooser setelahtgl;
    private javax.swing.JTable tbldataproduk;
    private javax.swing.JTable tbllaptransaksi;
    // End of variables declaration//GEN-END:variables
}
