/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasikasir_ujikom;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author user
 */
public class FormPelanggan extends javax.swing.JFrame {
    Connection konek;
    PreparedStatement pst;
    ResultSet rst;
    /**
     * Creates new form FormPelanggan
     */
    public FormPelanggan() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        konek = Koneksi.koneksiDB();
        updatetabel();
    }
    
    public void updatetabel() {
        try{
            String sql="select * from pelanggan";
             pst=konek.prepareStatement(sql);
             rst=pst.executeQuery();
            tblpelanggan.setModel (DbUtils.resultSetToTableModel(rst));
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
    }
    
    private void clear() {
        txtidpelanggan.setText("");
        txtnamapelanggan.setText("");
        txtalamat.setText("");
        txtnotelp.setText("");
        
        
    }
    
    private void simpan() {
         try{
            String sql= "insert into pelanggan (PelangganID,NamaPelanggan,Alamat,NoTelpon) value(?,?,?,?)";
            pst=konek.prepareStatement(sql);
            pst.setString(1, txtidpelanggan.getText());
             pst.setString(2, txtnamapelanggan.getText());
              pst.setString(3, txtalamat.getText());
               pst.setString(4, txtnotelp.getText());
               pst.execute();
                JOptionPane.showMessageDialog(null, "Data Tersimpan");
        }catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
                    }
        updatetabel();
        clear();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidpelanggan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnamapelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtnotelp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpelanggan = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PELANGGAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 100, 260, 50);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id Pelanggan ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 220, 80, 16);

        txtidpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(txtidpelanggan);
        txtidpelanggan.setBounds(310, 250, 120, 22);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Pelanggan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 300, 110, 16);
        getContentPane().add(txtnamapelanggan);
        txtnamapelanggan.setBounds(310, 330, 130, 22);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(310, 380, 70, 16);

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(310, 410, 220, 86);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No Telp");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 520, 70, 16);
        getContentPane().add(txtnotelp);
        txtnotelp.setBounds(310, 550, 140, 22);

        tblpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpelanggan);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(650, 270, 452, 120);

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan);
        btnsimpan.setBounds(670, 550, 74, 23);

        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit);
        btnedit.setBounds(800, 550, 75, 23);

        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus);
        btnhapus.setBounds(930, 550, 72, 23);

        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnkeluar);
        btnkeluar.setBounds(1050, 550, 72, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Camera Roll\\jaemin.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1959, 740);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpelangganActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
simpan();
clear();     // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
 try{
            
            String idpelanggan = txtidpelanggan.getText();
            String nmpelanggan = txtnamapelanggan.getText();
            String alamat = txtalamat.getText();
            String notelp = txtnotelp.getText();
            String sql= "update pelanggan set NamaPelanggan='"+nmpelanggan+"', Alamat='"+alamat+"', NoTelpon='"+notelp+"' where PelangganID='"+idpelanggan+"'";
            pst=konek.prepareStatement(sql);
            pst.execute();
                JOptionPane.showMessageDialog(null, "Data ber-hasil di ubah");
        }catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
                    }
        updatetabel();
        clear();
          // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
    try{
    String sql= "delete from pelanggan where PelangganID=?";
    pst=konek.prepareStatement(sql);
    pst.setString(1, txtidpelanggan.getText());
    pst.execute();
    JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus");
} catch(Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
updatetabel();
clear();
              // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void tblpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpelangganMouseClicked
    try { 
int baris=tblpelanggan.getSelectedRow();
String tabelKlik=(tblpelanggan.getModel().getValueAt(baris, 0).toString());
String sql="select * from pelanggan where PelangganID='"+tabelKlik+"'";
pst=konek.prepareStatement(sql);
rst=pst.executeQuery();
if (rst.next()) {
   String dataProdukID=rst.getString(("PelangganID"));
   txtidpelanggan.setText(dataProdukID);
   String dataNamaPelanggan=rst.getString(("NamaPelanggan"));
   txtnamapelanggan.setText(dataNamaPelanggan);
   String dataalamat=rst.getString(("Alamat"));
   txtalamat.setText(dataalamat);
   String datanotlp=rst.getString(("NoTelpon"));
   txtnotelp.setText(datanotlp );
}
    } catch (Exception e) {
     JOptionPane.showMessageDialog(null, e);
     
                                  
    }        // TODO add your handling code here:
    }//GEN-LAST:event_tblpelangganMouseClicked

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblpelanggan;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtidpelanggan;
    private javax.swing.JTextField txtnamapelanggan;
    private javax.swing.JTextField txtnotelp;
    // End of variables declaration//GEN-END:variables
}
